#!/usr/bin/python
# coding: utf-8

from glob import glob
import os
import subprocess

# Paramètres du script
extensions = ['.torrent']

dossiers_commandes = {
    'Jeux/': 
        'transmission-remote  --auth **:** -w /home/adriano/srv_apache/repository.scms.ovh/Jeux -a /home/adriano/srv_apache/up.scms.ovh/',
    'Chemin2/':
        'echo commande2'}

suppression = True

# Vérifier la présence de fichiers dans les dossiers
#
print('Démarrage...')

# Pour chaque chemin a verifier
for chemin_dossier in dossiers_commandes.keys():
    print('Vérification chemin "{}"...'.format(chemin_dossier))
    
    # Pour chaque type d'extension à rechercher
    for extension in extensions:
        print('\tVérification extension "{}"...'.format(extension))
        
        # On récupère une liste des fichiers avec l'extension
        fichiers_trouves_avec_extensions = glob(chemin_dossier + '*' + extension)
        print('\t{} fichiers trouvés.'.format(len(fichiers_trouves_avec_extensions)))
        
    # Pour chaque fichiers trouvé, 
    for fichier in fichiers_trouves_avec_extensions:

        print('\tExecution de la commande pour le fichier "{}"...'.format(fichier))
        
        # On récupère la commane
        commande = dossiers_commandes[chemin_dossier]
        
        # On la transforme en liste d'arguments
        commande = commande.split(' ')
        
        # On ajoute à la fin le nom du fichier
        commande[-1] = commande[-1] + fichier
        
        # On execute la commande
        subprocess.call(commande)

        if suppression:
            print('\tSuppression du fichier...')
            os.remove(fichier)
